# Template for mouse chip-seq using Illumina prepared samples
---
details:
- analysis: chip-seq
  # In order to do paired peak calling, samples should belong to the
  # same batch ("batch" under "metadata" below") and have a "phenotype"
  # field stating either "input" or chip". For each batch there
  # should be a sample with "chip" phenotype and a sample with "input"
  # phenotype (no more than two samples per batch)
  # macs2 narrow is default
  metadata:
     batch: your-batch-name
     phenotype: chip # or input
  genome_build: [mm10, GRCh37]
  algorithm:
    aligner: bowtie2
    adapters: [truseq]
    trim_reads: read_through
    peakcaller: [macs2]
  resources:
    macs2:
      options: ["-g mm"] or ["-g hs"](default)
      options: ["--broad", "-q 0.05"]

